services:
  - type: web
    name: telegram-chat-forward
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python forwarder.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
